dot_and_lines
yoav-zibin/shenkar pull request #20
Opened 2020-11-28 18:18 UTC by D10S60948

Changed the NYU code a bit and did what I could.

2020-12-01 12:31 UTC, yoav-zibin requested changes
I don't understand:
did you fix the old version of dots&Boxes?
https://github.com/yw1981/Dots_and_Boxes/blob/gh-pages/src/gameLogic.ts

Where is the gameLogic tests?
https://github.com/yw1981/Dots_and_Boxes/blob/gh-pages/src/gameLogic_test.ts

2020-12-01 12:31 UTC, yoav-zibin commented on .vscode/settings.json
> -    "editor.defaultFormatter": "esbenp.prettier-vscode",
please revert this file

2020-12-01 12:31 UTC, yoav-zibin commented on dots_and_lines/aiService.ts
> +// function getStateScoreForIndex0(move: IMove<any>[], playerIndex: number): number {
you can delete this comment :)

2020-12-01 12:31 UTC, yoav-zibin commented on package.json
> -    "@types/jest": "^26.0.14",
revert all files (except those related to dot_and_lines)

2020-12-02 18:39 UTC, D10S60948 commented
I pray to god it's fine now

2020-12-03 06:36 UTC, yoav-zibin requested changes
Much better 👍 
But I still think you have some bugs, so have another look and add tests.

For next HW, you can take 2 riddles from:

https://en.wikipedia.org/wiki/Dots_and_Boxes
One (Medium) from "Example game of Dots and Boxes on a 2 × 2 square board"
The second (Hard) from "The double-cross strategy: faced with position 1, a novice player would create position 2 and lose. An experienced player would create position 3 and win."

2020-12-03 06:36 UTC, yoav-zibin commented on dots_and_boxes/gameLogic.ts
> +    updatedBoard.turn === player.ONE ? updatedBoard.score.PLAYER_1++ : updatedBoard.score.PLAYER_2++;
This seems wrong. Please add more unit tests to cover more cases.

2020-12-05 08:20 UTC, D10S60948 commented
Bugs fixed and tests added

2020-12-06 12:50 UTC, barakdaniel commented on dots_and_boxes/__tests__/gameLogic_test.ts
> +import {IMove} from '../../common/common';
All needed here is to delete the specifics imports, if you are going to use them in the future you can just comment them right now.

2020-12-06 12:50 UTC, barakdaniel commented on dots_and_boxes/__tests__/gameLogic_test.ts
> +      var {direction, col, row} = move.state.delta;
Instead of using -  // eslint-disable-next-line no-var,
I think you can add a small object defining this build and use it for transferring the data.

2020-12-06 12:50 UTC, barakdaniel commented on dots_and_boxes/aiService.ts
> +import {AiService, IMove} from '../common/common';
Need some commenting in this file, there's no much code but there are some loops who needs explanation.

2020-12-06 12:50 UTC, barakdaniel commented on dots_and_boxes/gameLogic.ts
> +import {deepClone, IMove} from '../common/common';
This file required commenting as well

2020-12-16 18:24 UTC, closed without merging